### ISSUE TITLE
Broken documentation link in Readme.md

### ISSUE THREAD

**Issue by mgrassotti** [iotaledger/iota-area-codes#10]
Hi,

the link [https://docs.iota.org/docs/utils/0.1/official/iota-area-codes/overview](https://docs.iota.org/docs/utils/0.1/official/iota-area-codes/overview) indicated [here](https://github.com/iotaledger/iota-area-codes#getting-started):
```
# Getting started
For a tutorial on getting started with IACs, see our [documentation portal].
```

seems to be broken
<img width="300" alt="Schermata 2020-06-15 alle 23 34 42" src="https://user-images.githubusercontent.com/6908677/84708466-dc8a6500-af60-11ea-804e-d12110179a85.png">

**Comment by obany** [comment]
Thank you, fixed 👍
