### ISSUE TITLE
Query server DB_URL 

### ISSUE THREAD

**Issue by ouya99** [iotaledger/iota-area-codes#4]
What is **DB_URL=urls.go.here** supposed to be?

I did follow the guide to setup a server: 
Then in the end set DB_URL=cassandra:7000 , just some random value, since I do not know if this has to match with anything the docker-cassandra launch did setup (not so much familiar with docker nor cassandra)

After "yarn start" I see following output

```
$ micro 
Connecting to ZMQ
micro: Accepting connections on port 3000
```

**Comment by obany** [comment]
In our setup we just have the IP address of the machine running the cassandra server, so if you have it running locally I would suggest.
```
DB_URL=localhost
or
DB_URL=127.0.0.1
```

@l3wi might have more of an idea on this part.

**Comment by ouya99** [comment]
I changed DB_URL to 127.0.0.1

navigating to http://127.0.0.1:3000/initDatabase after "yarn start" does show "Not found" on web page.

**Comment by obany** [comment]
Ah, the initDatabase method is commented out as you only need it when first setting up the DB, if you uncomment these lines it should work.

https://github.com/iotaledger/iota-area-codes/blob/408a21bf4673998f92741476dc1ac9ac710ce2a5/examples/queryServer/index.js#L17-L25

**Comment by ouya99** [comment]
Thank you!

I followed https://medium.com/@marikalam/apache-cassandra-on-mac-os-x-installation-for-dummies-cc434b8da87 to setup the cassandra db and it worked!
