### ISSUE TITLE
Distance between 2 IACs

### ISSUE THREAD

**Issue by ouya99** [iotaledger/iota-area-codes#5]
Hi,

would you take a PR for this lib to calculate the (average, max, min, or other :)), distance between 2 IACs ? 
(by a) using a npm geo lib or b) direct plain calc ? )

Thanks

**Comment by obany** [comment]
I don't think we want to add features like this directly to the library, they detract from the purpose of the library and require additional maintenance.

The decode function can already provide the lat, lng for an IAC so I would recommend using an existing library such as https://www.npmjs.com/package/geolib from that point.
